In [70]:
import random
import requests
from bs4 import BeautifulSoup as bs
#import datetime
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine
from sqlalchemy.engine import url
import pypyodbc as odbc
import pandas as pd

In [71]:
import functions as fn

In [89]:
df = pd.read_csv('oldCSV/player Sal.csv')
df = df.dropna()
df

,Player,Terms,Pos,Status,Acquired,Age,Cap %,2023-24,Team
1,"Killorn, Alex",NTC,"RW, LW",NHL,Signed,34,7.5,"$6,250,000",ANA
2,"Henrique, Adam",M-NTC,"LW, C",NHL,Trade,33,7.0,"$5,825,000",ANA
3,"Silfverberg, Jakob ""A""",M-NTC,"RW, LW",NHL,Trade,33,6.3,"$5,250,000",ANA
9,"Carlsson, Leo",ELC,C,NHL,Draft,18,1.1,"$950,000",ANA
10,"McTavish, Mason",ELC,"C, LW",NHL,Draft,20,1.1,"$894,167",ANA
...,...,...,...,...,...,...,...,...,...
703,"Robertson, Nicholas",ELC,"LW, RW",NHL,Draft,22,1.0,"$796,667",TOR
706,"Rielly, Morgan ""A""",NMC,LD,NHL,Draft,29,9.0,"$7,500,000",TOR
707,"Brodie, TJ",M-NTC,LD/RD,NHL,Signed,33,6.0,"$5,000,000",TOR
708,"McCabe, Jake",RSM-NTC,LD/RD,NHL,Trade,30,2.4,"$2,000,000",TOR
710,"Giordano, Mark",35+,LD,NHL,Trade,40,1.0,"$800,000",TOR

In [94]:
df[['lName','fName']] = df['Player'].str.split(', ', expand=True)

In [95]:
df = df.drop(columns={'Player'})
df

,Terms,Pos,Status,Acquired,Age,Cap %,2023-24,Team,lName,fName
1,NTC,"RW, LW",NHL,Signed,34,7.5,"$6,250,000",ANA,Killorn,Alex
2,M-NTC,"LW, C",NHL,Trade,33,7.0,"$5,825,000",ANA,Henrique,Adam
3,M-NTC,"RW, LW",NHL,Trade,33,6.3,"$5,250,000",ANA,Silfverberg,"Jakob ""A"""
9,ELC,C,NHL,Draft,18,1.1,"$950,000",ANA,Carlsson,Leo
10,ELC,"C, LW",NHL,Draft,20,1.1,"$894,167",ANA,McTavish,Mason
...,...,...,...,...,...,...,...,...,...,...
703,ELC,"LW, RW",NHL,Draft,22,1.0,"$796,667",TOR,Robertson,Nicholas
706,NMC,LD,NHL,Draft,29,9.0,"$7,500,000",TOR,Rielly,"Morgan ""A"""
707,M-NTC,LD/RD,NHL,Signed,33,6.0,"$5,000,000",TOR,Brodie,TJ
708,RSM-NTC,LD/RD,NHL,Trade,30,2.4,"$2,000,000",TOR,McCabe,Jake
710,35+,LD,NHL,Trade,40,1.0,"$800,000",TOR,Giordano,Mark